name: Publish Package to NPM

on:
  release:
    types: [created]

jobs:
  release:
    name: Publish to NPM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: |
          if [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi

      - name: Publish to NPM
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          tag: ${{ steps.get_version.outputs.VERSION }}
