name: Publish Package to npmjs

on:
  release:
    types: [created]

jobs:
  release:
    name: publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: install and build
        run: |
          if [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi
      - name: publish
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          tag: ${{ steps.get_version.outputs.VERSION }}
